import type { Metadata } from "next";
import "@/shared/styles/globals.css";
import { Header } from "@/shared/components/molecules/Header";
import "bootstrap-icons/font/bootstrap-icons.css";
import Sidebar from "@/widgets/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
          <Header />
          <div className="flex w-full desktop:py-19 laptop:py-15 py-15">
            <Sidebar />
            <div className="w-full flex-1 desktop:py-7 laptop:py-5 px-5 py-5 font-sans min-h-screen bg-[#F9FAFB] dark:bg-[#121826]">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
