import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/shared/components/molecules/Header";
import "bootstrap-icons/font/bootstrap-icons.css";
import Sidebar from "@/shared/components/molecules/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="flex">
          <Sidebar />
          <main className="flex-1 p-6">{children}</main>
        </div>
      </body>
    </html>
  );
}
