import type { Metadata } from "next";
import "@/shared/styles/globals.css";
import { Header } from "@/shared/components/molecules/Header";
import "bootstrap-icons/font/bootstrap-icons.css";
import Sidebar from "@/widgets/Sidebar";
import MobileMenu from "@/widgets/MobileMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <main className="flex flex-col min-h-screen">
          <Header />
          <div className="flex w-full flex-1 desktop:pt-19 laptop:pt-15 pt-15">
            <Sidebar />
            <div className="w-full flex-1 desktop:pt-7 laptop:pt-5 px-5 pt-5 font-sans bg-[#F9FAFB] dark:bg-[#121826] laptop:pb-10 overflow-auto mobile:pb-28">
              {children}
            </div>
          </div>
          <MobileMenu />
        </main>
      </body>
    </html>
  );
}
